services:
  anpr:
    build: .
    restart: no
    volumes:
      - ./in:/app/in
      - ./out:/ultralytics/runs/detect
#    devices:
#      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
